<?php

namespace RafaelSantiago\TesouroDiretoBundle\Entity\Repository;
use RafaelSantiago\TesouroDiretoBundle\Entity\Titulo;

/**
 * TituloHistoricoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TituloHistoricoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUltimaCotacao(Titulo $objTitulo)
    {

        $arrHistoricos = $this->getEntityManager()->createQueryBuilder()
            ->select('tituloHistorico')
            ->from('RafaelSantiagoTesouroDiretoBundle:TituloHistorico','tituloHistorico')
            ->where('tituloHistorico.titulo = :tituloTesouroId')
            ->setParameter('tituloTesouroId', $objTitulo->getTitulo()->getId())
            ->orderBy('tituloHistorico.data', 'DESC')
            ->getQuery()
            ->execute();

        return (count($arrHistoricos)) ? $arrHistoricos[0] : false;

    }
}
