<?php

namespace RafaelSantiago\TesouroDiretoBundle\Entity\Repository;

/**
 * TituloHistoricoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TituloHistoricoRepository extends \Doctrine\ORM\EntityRepository
{
}
