<?php

namespace RafaelSantiago\TesouroDiretoBundle\Entity\Repository;

/**
 * TituloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TituloRepository extends \Doctrine\ORM\EntityRepository
{

    public function getValorInvestido()
    {
        $arrTitulos = $this->getEntityManager()->createQueryBuilder()
            ->select('titulo')
            ->from('RafaelSantiagoTesouroDiretoBundle:Titulo', 'titulo')
            ->where('titulo.data_vencimento >= :data')
            ->setParameter('data', new \DateTime())
            ->getQuery()
            ->execute();

        $valor = 0;
        foreach ($arrTitulos as $titulo){
            $valor += $titulo->getValorInvestido();
        }

        return $valor;

    }

    public function getValorCarteira()
    {
        $arrTitulos = $this->getEntityManager()->createQueryBuilder()
            ->select('titulo')
            ->from('RafaelSantiagoTesouroDiretoBundle:Titulo', 'titulo')
            ->where('titulo.data_vencimento >= :data')
            ->setParameter('data', new \DateTime())
            ->getQuery()
            ->execute();

        $valor = 0;
        foreach ($arrTitulos as $titulo){
            $valor += ($titulo->getQuantidade() * $titulo->getTitulo()->getValorVenda());
        }

        return $valor;
    }

}
