services:
    twig.extension.titulo_profit:
        class: RafaelSantiago\TesouroDiretoBundle\Twig\ProfitExtension
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }
